//! tonic/prost-generated gRPC API (see `proto/` and `build.rs`). The
//! generated code and descriptor are committed so builds work without
//! `protoc` installed.

#[path = ""]
pub mod equalizer {
    /// Encoded FileDescriptorSet for gRPC server reflection (grpcurl etc.).
    pub const FILE_DESCRIPTOR_SET: &[u8] = include_bytes!("descriptor.bin");

    // rustfmt::skip: the file is regenerated by tonic-build (prettyplease
    // formatting), so letting rustfmt touch it would make `fmt --check`
    // and codegen fight forever.
    #[allow(clippy::all, clippy::pedantic)]
    #[rustfmt::skip]
    #[path = "equalizer.v1.rs"]
    pub mod v1;
}
