name: Nix

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  nix-build:
    name: nix build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Cachix
        uses: cachix/cachix-action@v17
        with:
          name: tsirysndr
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build
        run: nix build .#default --print-build-logs

      - name: Show result
        run: ls -l result/bin && ./result/bin/equalizer --version
